#!/bin/bash
argc=$#
argv=("$@")

touch Engine/include/$1.hpp
echo "#pragma once
#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>
" >> Engine/include/$1.hpp

for (( j=1; j<argc; j++ ))
do
    echo "#include \"${argv[j]}.hpp\"" >> Engine/include/$1.hpp
done

echo "
class $1
{

};" >> Engine/include/$1.hpp
touch Engine/src/$1.cpp
echo "#include \"../include/$1.hpp\"" >> Engine/src/$1.cpp